server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    # master config
    master:
      url: jdbc:mysql://localhost:3306/db_master?characterEncoding=utf-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    # slave config
    slave:
      url: jdbc:mysql://localhost:3307/db_slave?characterEncoding=utf-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver

# mybatis config
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
