server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  datasource:
    # master config
    master:
      url: jdbc:mysql://192.168.1.102:3306/test?characterEncoding=utf-8
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    # slave config
    slave:
      url: jdbc:mysql://192.168.1.103:3306/test?characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

# mybatis config
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
